name: Test

on: [push]

jobs:
  test:
    name: Test-Action
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Test
        id: test
        uses: ./
        with:
          webhook: ${{ secrets.WEBHOOK }}
          message: This is a test message!